# 阶段1：应用编译（启用静态链接）
FROM docker.1ms.run/rust:latest AS builder
WORKDIR /app
RUN sed -i 's@deb.debian.org@repo.huaweicloud.com@g' /etc/apt/sources.list.d/debian.sources
RUN apt update && apt install -y musl-tools
RUN RUSTUP_DIST_SERVER="https://rsproxy.cn" \ 
    RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup" \
    rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cargo build --target x86_64-unknown-linux-musl --release

# 阶段2：最小化运行时镜像
FROM scratch
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/cloudflare-ddns-ipv6 /
CMD ["/cloudflare-ddns-ipv6"]